### PR TITLE
feat: allow exact values

### PR DESCRIPTION
**Pull request by mja00**
This just disables the inline comment escaping

### CODE REVIEW

**Review by Cherry — CHANGES_REQUESTED** [review]
This looks great, thanks! Can we update the README with some basic details about this new `exactValue` option please?

**Comment by Cherry** [comment]
I also wonder if it might be better to simply only look at `;` comments if they have some whitespace before them.

So:
```
foo=bar;baz;bap ; comment
```
would parse as `bar;baz;bap`. That does seem to be a pretty common approach from the quick searching I've done.

**Comment by mja00** [comment]
> I also wonder if it might be better to simply only look at ; comments if they have some whitespace before them.

Would we want to check for spaces all around the character or just after it? 

IE: `blah; this would trigger a comment`
or 
`blah ; this would trigger a comment`

where we'd stop parsing on the space so it'd just come out as `blah`.

**Comment by Cherry** [comment]
There seems to be some consensus (as much as you get can get for `ini`) that any whitespace before a `;` then indicates a comment? What do you think?

**Comment by mja00** [comment]
> There seems to be some consensus (as much as you get can get for `ini`) that any whitespace before a `;` then indicates a comment? What do you think?

Yeah makes sense to me. It's easy enough in the parser to check for whitespace around the comment character.

**Review by Cherry — APPROVED** [review]

**Pull request merged**
